### ISSUE TITLE
Errors (ChatPrefixer)

### ISSUE THREAD

**Issue by Kotemas** [Caelum100/ChatPrefixer#1]
[02:22:24] [Async Chat Thread - #82/ERROR]: Could not pass event AsyncPlayerChatEvent to ChatPrefixer v1.1
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[spigot.jar:git-Spigot-ed1cec9-1a6b4f5]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-ed1cec9-1a6b4f5]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot.jar:git-Spigot-ed1cec9-1a6b4f5]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:482) [spigot.jar:git-Spigot-ed1cec9-1a6b4f5]
	at net.minecraft.server.v1_13_R1.PlayerConnection.chat(PlayerConnection.java:1556) [spigot.jar:git-Spigot-ed1cec9-1a6b4f5]
	at net.minecraft.server.v1_13_R1.PlayerConnection.a(PlayerConnection.java:1494) [spigot.jar:git-Spigot-ed1cec9-1a6b4f5]
	at net.minecraft.server.v1_13_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:39) [spigot.jar:git-Spigot-ed1cec9-1a6b4f5]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_131]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_131]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
Caused by: java.lang.IllegalArgumentException: character to be escaped is missing
	at java.util.regex.Matcher.appendReplacement(Unknown Source) ~[?:1.8.0_131]
	at java.util.regex.Matcher.replaceAll(Unknown Source) ~[?:1.8.0_131]
	at java.lang.String.replaceAll(Unknown Source) ~[?:1.8.0_131]
	at net.caelum100.chatprefixer.ChatListener.onChat(ChatListener.java:34) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor475.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_131]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[spigot.jar:git-Spigot-ed1cec9-1a6b4f5]
	... 11 more

**Comment by caelunshun** [comment]
Sorry for not seeing this issue in time. I'll see what I can do.
